AppCoder/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from AppCoder import views


app_name = "AppCoder"
urlpatterns = [

    path('inicio', views.inicio, name='Inicio'),
    path('cursos', views.cursos, name='Cursos'),
    path('profesores', views.profesores, name='Profesores'),
    path('estudiantes', views.estudiantes, name='Estudiantes'),
    path('entregables', views.entregables, name='Entregables'),
    path('buscar/', views.buscar),
    path('leerProfesores', views.leerProfesores, name='LeerProfesores'),
    path('eliminarProfesor/<profesor_nombre>/',views.eliminarProfesor, name="EliminarProfesor"),
    path('editaProfesor/<profesor_nombre>', views.editarProfesor, name = 'EditarProfesor'),
    path('curso/list', views.CursoList.as_view(), name='List'),
    path('<int:pk>', views.CursoDetalle.as_view(), name='Detail'),
    path('nuevo', views.CursoCreacion.as_view(), name='New'),
    path('editar/<int:pk>', views.CursoUpdate.as_view(), name='Edit'),
    path('borrar/<int:pk>', views.CursoDelete.as_view(), name='Delete'),
    path('', views.login_request, name='Login' ),
    path('register', views.register, name= 'Register'),
    path('logout', LogoutView.as_view(template_name='logout.html'), name='Logout'),
    path('editarPerfil', views.editarPerfil, name='EditarPerfil'),
    path('agregarAvatar', views.agregarAvatar, name='AgregarAvatar'),
    path('custom_404', views.custom_404, name='Custom_404'),
    path('proximamente', views.proximamente, name='Proximamente'),
    path('login_invitado/', views.login_invitado, name='Login_invitado'),
    path('aboutus', views.aboutus, name='About_Us'),

]

AppCoder/templates/agregarAvatar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <title>Cargar Avatar</title>
</head>
<body>

    <h3>Cargar Avatar</h3>
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        {{ miFormulario.as_p  }}
      

        <input type="submit" value="Actualizar">


    </form>


    
</body>
</html>

AppCoder/templates/cursos.html
{% extends 'padre.html'%}

{% load static %}

{% block contenidoQueCambia%}
        <div class="text-center">
            <img height="80px" src="{{url}}" />
            <h3>Hola {{user.username}}</h3>
        </div>

    <!--Colocamos lo que va a cambiar -->
    <header class="masthead">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <div class="text-center text-white">
                        <!-- Page heading-->
                        <h1 class="mb-5">Cursos</h1>
                        <h2>Django - CoderHouse</h2>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <h1>Agregar Curso/s</h1>
    {% if miFormulario.errors %}
    <p style="color:red;">Estan mal los datos, revisar.</p>
    {% endif %}

    <form action="" method="POST">{% csrf_token %}
       
       <table>
            {{miFormulario.as_table}}
       </table>

        <input type="submit" value="Enviar">
    </form>

{% endblock %}

AppCoder/templates/entregables.html
{% extends 'padre.html'%}

{% load static %}

{% block contenidoQueCambia%}
        <div class="text-center">
            <img height="80px" src="{{url}}">
            <h3>Hola {{user.username}}</h3>
        </div>

    <!--Colocamos lo que va a cambiar -->
    <header class="masthead">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <div class="text-center text-white">
                        <!-- Page heading-->
                        <h1 class="mb-5">Entregables</h1>
                        <h2>Django - CoderHouse</h2>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <h1>Agregar Entregable</h1>
    {% if miFormulario.errors %}
    <p style="color:red;">Estan mal los datos, revisar.</p>
    {% endif %}

    <form action="" method="POST">{% csrf_token %}
       
       <table>
            {{miFormulario.as_table}}
       </table>

        <input type="submit" value="Enviar">
    </form>

{% endblock %}

AppCoder/templates/estudiantes.html
{% extends 'padre.html'%}

{% load static %}

{% block contenidoQueCambia%}
        <div class="text-center">
            <img height="80px" src="{{url}}">
            <h3>Hola {{user.username}}</h3>
        </div>

    <!--Colocamos lo que va a cambiar -->
    <header class="masthead">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <div class="text-center text-white">
                        <!-- Page heading-->
                        <h1 class="mb-5">Estudiantes</h1>
                        <h2>Django - CoderHouse</h2>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <h1>Agregar Estudiante/s</h1>
    {% if miFormulario.errors %}
    <p style="color:red;">Estan mal los datos, revisar.</p>
    {% endif %}

    <form action="" method="POST">{% csrf_token %}
       
       <table>
            {{miFormulario.as_table}}
       </table>

        <input type="submit" value="Enviar">
    </form>

{% endblock %}

AppCoder/templates/inicio.html
{% extends 'padre.html'%}

{% load static %}

{% block contenidoQueCambia%}
        <div class="text-center">
            <img height="80px" src="{{url}}" />
            <h3>Hola {{user.username}}</h3>
        </div>

    <!--Colocamos lo que va a cambiar -->
    <header class="masthead">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <div class="text-center text-white">
                        <!-- Page heading-->
                        <h1 class="mb-5">Mi primera web Intermedia!</h1>
                        <h2>Django - CoderHouse</h2>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% if mensaje %}
    <h5>
    <p>{{mensaje}}</p>
    </h5>
    {% endif %}

    <h1>Busqueda de Camadas</h1>
    <form action="/AppCoder/buscar/" method="GET">

        <input type="number" name="camada" id="camada">

        <input type="submit" value="Buscar">
    </form>

    <p>Estamos buscando la camada: {{camada}}</p>

    {% if cursos %}

    <ul>
        {% for curso in cursos %}
            <li> {{curso.nombre}}</li>
            <li>{{curso.camada}}</li>
        {% endfor %}
    </ul>
    {% endif %}

{% endblock %}
<p style="color:red">{{respuesta}}</p>

AppCoder/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            background-image: url("/media/avatares/login.jpg");
            background-size: cover;
        }
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        form {
            max-width: 400px;
            width: 100%;
            padding: 50px;
            border: 1px solid #ccc;
            border-radius: 55px;
            background-color: aliceblue;
        }
        button {
            margin-top: 10px;
        }
    </style>
</head>
<body>


    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" style="background-color: rgb(215, 128, 226);">Iniciar Sesión</button>
            <button type="submit" name="login_invitado" value="true" style="background-color: rgb(192, 192, 192);">Ingresar como invitado</button>
        </form>
    </div>


    
</body>
</html>

AppCoder/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AppCoder - logout</title>
    <style>
        body {
            background-image: url("/media/avatares/login.jpg");
            background-size: cover;
        }
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        form {
            max-width: 400px;
            width: 100%;
            padding: 50px;
            border: 1px solid #ccc;
            border-radius: 55px;
            background-color: aliceblue;
        }
        button {
            margin-top: 10px;
        }

        h1 {
            font-size:24px;
            font-weight: bold;
            margin-bottom: 20px;

        }

        .btn-primary {
            background-color: rgb(9, 169, 243);
            color:black;
            border: none;
            padding: 10px;
            border-radius: 5px;
            font-size: 16px;
            font-weight: bold;
            text-decoration: none;
        }

        .btn-primary:hover{
            background-color: black;
            color: azure;
        }
    </style>
</head>
<body>
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
        <h1>Has cerrado sesion.</h1>
         <a class="btn btn-primary" href="{% url 'AppCoder:Login' %}">Volver al Ingresar</a>
        </form>

    </div>
    
</body>
</html>

AppCoder/templates/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Proyecto Coder</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppCoder/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'AppCoder/css/bootstrap.min.css' %}" rel="stylesheet" >
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    </head>
    <body>
        </form>
        <!-- Navigation-->
  <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'AppCoder:Inicio' %}">Inicio</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Cursos' %}"> Cursos</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Estudiantes' %}"> Estudiantes</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Profesores' %}"> Profesores</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Entregables' %}"> Entregables</a>
                {% if not request.user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'AppCoder:Login' %}">Iniciar Sesión</a>
                {% endif %}

                {% if request.user.is_authenticated %}
                
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
                        <img height="30px" src="{{url}}" />
                        <span class="caret"></span>
                        {{user.username}}
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'AppCoder:EditarPerfil' %}">Editar Perfil</a>
                        <a class="dropdown-item" href="{% url 'AppCoder:AgregarAvatar' %}">Agregar Avatar</a>
                        <a class="dropdown-item" href="{% url 'AppCoder:Logout' %}">Cerrar Sesión</a>
                    </div>
                </div>
                {% endif %}
               
            </div>
        </nav>
        <!-- Masthead-->

            </div>        
        {% block contenidoQueCambia %}
        {% endblock %}

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Franco Romero 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'AppCoder/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

AppCoder/templates/profesores.html
{% extends 'padre.html'%}

{% load static %}

{% block contenidoQueCambia%}
        <div class="text-center">
            <img height="80px" src="{{url}}">
            <h3>Hola {{user.username}}</h3>
        </div>

    <!--Colocamos lo que va a cambiar -->
    <header class="masthead">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <div class="text-center text-white">
                        <!-- Page heading-->
                        <h1 class="mb-5">Profesores</h1>
                        <h2>Django - CoderHouse</h2>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <h1>Agregar profesor/es</h1>
    {% if miFormulario.errors %}
    <p style="color:red;">Estan mal los datos, revisar.</p>
    {% endif %}

    <form action="" method="POST">{% csrf_token %}
       
       <table>
            {{miFormulario.as_table}}
       </table>

        <input type="submit" value="Enviar">
    </form>

{% endblock %}

AppCoder/templates/proximamente.html
{% extends 'padre.html'%}

{% load static %}

{% block contenidoQueCambia%}

    <!--Colocamos lo que va a cambiar -->
    <header class="masthead">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <div class="text-center text-white">
                        <!-- Page heading-->
                        <h1 class="mb-5">Proximamente... </h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <main class="">
        <div>
            <div></div>
        </div><p></p>
    </main>
{% endblock %}